TOAST_CHECK_FIELDS = [
    "customer",
    "opened_date",
    "opened_time",
    "item_description",
    "server",
    "tax",
    "tender",
    "check_id",
    "check_number",
    "total",
    "customer_family",
    "table_size",
    "discount",
    "reason_of_discount",
    "link",
]

TOAST_ORDER_FIELDS = [
    "pk",
    "id",
    "order_id",
    "order_number",
    "checks",
    "opened",
    "number_of_guests",
    "tab_names",
    "server",
    "table",
    "revenue_center",
    "dining_area",
    "service",
    "dining_options",
    "discount_amount",
    "amount",
    "tax",
    "tip",
    "gratuity",
    "total",
    "voided",
    "paid",
    "closed",
    "duration_opened_to_paid",
    "order_source",
    "toast_auth__unit__pk",
    "user",
    "toast_auth__block_category__pk",
]


RESY_RESERVATION_FIELDS = [
    "resy_auth",
    "time",
    "reservation_date",
    "service",
    "phone",
    "email",
    "party_size",
    "status",
    "table",
    "visit_note",
    "reserve_number",
    "user",
    "datetime",
    "resy_auth__unit__pk",
    "guest",
    "resy_auth__block_category__pk",
]

TOAST_ITEM_SELECTION_FIELDS = [
    "toast",
    "order",
    "order_date",
    "check_id",
    "server",
    "table",
    "dining_area",
    "service",
    "dining_option",
    "item_selection_id",
    "item_id",
    "master_id",
    "sku",
    "plu",
    "menu_item",
    "menu_subgroups",
    "menu_group",
    "menu",
    "sales_category",
    "gross_price",
    "discount",
    "net_price",
    "quantity",
    "tax",
    "void",
    "deferred",
    "tax_exempt",
    "tax_inclusion_option",
    "dining_option_tax",
    "tab_name" "toast__unit__pk",
]

TOAST_PAYMENT_FIELDS = [
    "payment_id",
    "paid_date",
    "order_date",
    "check_id",
    "check_number",
    "tab_name",
    "server",
    "table",
    "dining_area",
    "service",
    "dining_option",
    "house_account",
    "amount",
    "tip",
    "gratuity",
    "total",
    "swiped_card_amount",
    "keyed_card_amount",
    "amount_tendered",
    "refunded",
    "refund_date",
    "refund_amount",
    "refund_tip_amount",
    "void_user",
    "void_approver",
    "void_date",
    "status",
    "type",
    "cash_drawer",
    "card_type",
    "other_type",
    "last_4_card_digits",
    "vmcd_fees",
    "room_info",
    "receipt",
    "source",
]

TOAST_TIME_ENTRIES_FIELDS = [
    "time_entry_id",
    "guid",
    "employee_id",
    "employee_guid",
    "employee_external_id",
    "employee",
    "job_id",
    "job_guid",
    "job_code",
    "job_title",
    "in_date",
    "out_date",
    "auto_clock_out",
    "total_hours",
    "unpaid_break_time",
    "paid_break_time",
    "payable_hours",
    "cash_tips_declared",
    "non_cash_tips",
    "total_gratuity",
    "total_tips",
    "tips_withheld",
    "wage",
    "regular_hours",
    "overtime_hours",
    "regular_pay",
    "overtime_pay",
    "total_pay",
]

REPORT_USER_FIELDS = [
    "pk",
    "id",
    "brand",
    "brand__name",
    "email",
    "phone",
    "first_name",
    "last_name",
]

TOCK_BOOKING_FIELDS = [
    "pk",
    "tock",
    "time",
    "status",
    "dietary_notes",
    "tags",
    "postal_code",
    "party_size",
    "booking_owner",
    "user",
    "experience",
    "price_per_person",
    "supplements",
    "question_answers",
    "visit_notes",
    "visit_dietary_notes",
    "guest_provided_order_notes",
    "guest_notes",
    "total_price",
    "gross_amount_paid",
    "net_amount_paid",
    "service_charge",
    "gratuity",
    "confirmation",
    "visits",
    "last_visit_date",
    "last_visit_time",
    "group_visits",
    "spouse_name",
    "birthday",
    "booking_method",
    "modified_by",
    "final_status",
    "tables",
    "servers",
    "dining_time_seconds",
    "tock__unit__pk",
    "tock__block_category__pk",
]


TOAST_ORDER_SERIALIZED_RECORD_SIZE = 700  # actual value: 599
TOAST_PAYMENT_SERIALIZED_RECORD_SIZE = 500  # actual value: 358
TOAST_ITEM_SELECTION_DETAILS_SERIALIZED_RECORD_SIZE = 900  # actual value: 758
REPORT_USER_SERIALIZED_RECORD_SIZE = 300  # actual value : 158
RESY_RESERVATION_SERIALIZED_RECORD_SIZE = 500  # actual value: 357
