from .conversation import Conversation
from .department import Department
from .emergency_contact import EmergencyContact
from .emotional_analysis import EmotionalAnalysis
from .employee import Employee
from .employment_detail import EmploymentDetail
from .knowledge_base_contribution import KnowledgeBaseContribution
from .manager import Manager
from .performance_record import PerformanceRecord
from .personal_information import PersonalInformation
from .technical_metadata import TechnicalMetaData
from .training_development import TrainingAndDevelopment
from .voice_interaction import VoiceInteraction
