steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/xblock:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/xblock:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run with secrets from Secret Manager
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'xblock'
      - '--image'
      - 'gcr.io/$PROJECT_ID/xblock:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '1Gi'
      - '--timeout'
      - '300s'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--update-secrets'
      - 'SECRET_KEY=xblock-secret-key:latest,DATABASE_PASSWORD=xblock-db-password:latest,GCP_CREDENTIALS=xblock-gcp-credentials:latest,INTEGRATIONS_CREDENTIALS=xblock-integrations-credentials:latest'
      - '--set-env-vars'
      - 'DEBUG=False,DATABASE_NAME=xblock,DATABASE_USER=xblock,DATABASE_HOST=db,DATABASE_PORT=5432,GOOGLE_APPLICATION_CREDENTIALS=/tmp/keys/gcp-credentials.json'

images:
  - 'gcr.io/$PROJECT_ID/xblock:$COMMIT_SHA'

timeout: '1200s'
