# cloudbuild.prod.yaml
steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/xblock-gcp-cloudrun:${COMMIT_SHA}' # Tag with commit SHA for versioning
      - '.' # Dockerfile location
    id: 'Build Docker Image'

  # Push the Docker image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/xblock-gcp-cloudrun:${COMMIT_SHA}'
    id: 'Push Image to GCR'
    waitFor:
      - 'Build Docker Image'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'xblock-service' # Name of the Cloud Run service
      - '--image=gcr.io/$PROJECT_ID/xblock-gcp-cloudrun:${COMMIT_SHA}'
      - '--region=us-central1' # Specify your desired region
      - '--platform=managed'
      - '--allow-unauthenticated' # Or configure IAM for authentication
      - '--port=${_PORT_ENV_VAR}' # Use a substitution for the port
      - '--set-env-vars=DJANGO_SETTINGS_MODULE=xblock.settings'
      # Add any other environment variables required by your application
      # - '--set-env-vars=DJANGO_SECRET_KEY=your-production-secret-key' # This should be a secret
      # - '--set-env-vars=DJANGO_DEBUG=False'
    id: 'Deploy to Cloud Run'
    waitFor:
      - 'Push Image to GCR'

substitutions:
  _PORT_ENV_VAR: '8080' # Default port, can be overridden

images:
  - 'gcr.io/$PROJECT_ID/xblock-gcp-cloudrun:${COMMIT_SHA}'

options:
  logging: CLOUD_LOGGING_ONLY
