# Test Cloud Build Configuration with minimal Hello World sample

steps:
  # Build the container image using the Hello World sample
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/xblock-test:$COMMIT_SHA', '-f', 'Dockerfile.hello', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/xblock-test:$COMMIT_SHA']
  
  # Deploy a new test service (no environment variables or secrets)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'xblock-test'  # New service name
      - '--image'
      - 'gcr.io/$PROJECT_ID/xblock-test:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '1Gi'
      - '--timeout'
      - '300s'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'

images:
  - 'gcr.io/$PROJECT_ID/xblock-test:$COMMIT_SHA'

# Timeout for the build process
timeout: '1200s'
