
name: 'hub-main'
# version: '3.12'

services:


  # weaviate:
  #   command:
  #     - --host
  #     - 0.0.0.0
  #     - --port
  #     - '8080'
  #     - --scheme
  #     - http
  #   networks:
  #     - xbrain
  #   image: semitechnologies/weaviate:1.24.2
  #   ports:
  #     - 8080:8080
  #     # - 3000:8080
  #   expose:
  #     - 8080
  #   volumes:
  #     - weaviate_data:/var/lib/weaviate
  #   restart: on-failure:0
  #   healthcheck:
  #     test: wget --no-verbose --tries=3 --spider http://localhost:8080/v1/.well-known/ready || exit 1
  #     interval: 5s
  #     timeout: 10s
  #     retries: 5
  #     start_period: 10s
  #   environment:
  #     OPENAI_APIKEY: $OPENAI_API_KEY
  #     COHERE_APIKEY: $COHERE_API_KEY
  #     QUERY_DEFAULTS_LIMIT: 25
  #     AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
  #     PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
  #     ENABLE_MODULES: 'text2vec-openai, generative-openai, qna-openai, text2vec-cohere'
  #     CLUSTER_HOSTNAME: 'node1'

  web:
    networks:
        - xbrain
    build: .
    restart: always
    command: bash run.sh
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      - db
    environment:
      - DEBUG=1

  db:
    networks:
      - xbrain
      
    restart: always
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=xblock
      - POSTGRES_PASSWORD=Xblock123456
      - POSTGRES_DB=xblock
    ports:
      - 5432:5432

  # frontend:
  #   build: ./frontend
  #   volumes:
  #     - ./frontend:/usr/src/app
  #     - /usr/src/app/node_modules
  #   ports:
  #     - 3000:3000
  #   environment:
  #     - NODE_ENV=development
  #   depends_on:
  #     - web

  redis:
    networks:
      - xbrain

    restart: always
    image: redis:alpine
    ports:
      - 6379:6379
    # volumes:
    #   - redis_data:/data

  celery:
    build: .
    restart: always
    command: celery -A xblock worker --loglevel=info
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - web
      - redis

    networks:
      - xbrain
  
  beat:
    restart: always
    build: .
    command: celery -A xblock beat -S redbeat.RedBeatScheduler --loglevel=info
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - web
      - redis

    networks:
      - xbrain

  # selenium:
  #     image: seleniarm/standalone-firefox
  #     ports:
  #       - 4444:4444
      
  #     volumes:
  #       - ./selenium:/home/seluser/Downloads
      
  #     networks:
  #       - xbrain
  #     # entrypoint: ["sleep 10; sudo chown seluser:seluser -R /home/seluser/Downloads"]

  flower:
     restart: always
     networks:
      - xbrain
     build: .
     command: celery -A xblock --broker=redis://redis:6379/0 flower --port=5555 --basic-auth="hyiqiu23@gmail.com:hyq5566123"
     volumes:
       - ./:/usr/src/app/
     ports:
       - 5555:5555
     depends_on:
       - celery
       - beat
       - redis

volumes:
  weaviate_data: {}
  postgres_data:
  # redis_data:

networks:
  xbrain:
    driver: bridge