apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: xblock
spec:
  template:
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: gcr.io/xbrain-422617/xblock:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
        envFrom:
        - secretRef:
            name: backend-env
        - name: PORT
          value: "8080"
