from django.contrib import admin
from customer.models import (
    Address,
    AIInteractionMetadata,
    CompetitiveAnalysis,
    ContactInformation,
    CustomerCommunication,
    CustomerEnrichmentData,
    CustomerFeedback,
    CustomerLifetimeValue,
    CustomerSegmentation,
    Customer,
    LeadSource,
    LoyaltyProgram,
    MarketingPreference,
    NoteAndActivity,
    PurchaseHistory,
    SocialMediaProfile,
    SupportAssistantRecord,
    TechnicalMetaData,
    TradeAreaAnalysis,
    CustomerLocationBehavior,
    WebsiteInteraction,
    CustomerDemographic,
    SupportTicket,
    XBrainCustomerInteraction,
    XBrainConversationLog,
    PurchaseAssistantRecord,
    ItemPurchased,
)


admin.site.register(Address)
admin.site.register(AIInteractionMetadata)
admin.site.register(CompetitiveAnalysis)
admin.site.register(ContactInformation)
admin.site.register(CustomerCommunication)
admin.site.register(CustomerEnrichmentData)
admin.site.register(CustomerFeedback)
admin.site.register(CustomerLifetimeValue)
admin.site.register(CustomerSegmentation)
admin.site.register(Customer)
admin.site.register(LeadSource)
admin.site.register(LoyaltyProgram)
admin.site.register(MarketingPreference)
admin.site.register(NoteAndActivity)
admin.site.register(PurchaseHistory)
admin.site.register(SocialMediaProfile)
admin.site.register(SupportAssistantRecord)
admin.site.register(TechnicalMetaData)
admin.site.register(TradeAreaAnalysis)
admin.site.register(CustomerLocationBehavior)
admin.site.register(WebsiteInteraction)
admin.site.register(CustomerDemographic)
admin.site.register(SupportTicket)
admin.site.register(XBrainCustomerInteraction)
admin.site.register(XBrainConversationLog)
admin.site.register(PurchaseAssistantRecord)
admin.site.register(ItemPurchased)
